services:
  db:
    build: ./requirements/mariadb/
    restart: unless-stopped
    volumes:
      - ~/data/database:/var/lib/mariadb
    networks:
      - inception
    secrets:
      - db_user
      - db_password
      - db_name
  nginx:
    build: ./requirements/nginx/
    restart: unless-stopped
    depends_on:
      - wordpress
    ports:
      - "443:443"
    networks:
      - inception
  wordpress:
    build: ./requirements/wordpress/
    restart: unless-stopped
    depends_on:
      - db
    volumes:
      - ~/data/wordpress:/var/www/html
    networks:
      - inception
    secrets:
      - db_user
      - db_password
      - db_name

networks:
  inception:

secrets:
  db_user:
    file: ../secrets/db_user.txt
  db_password:
    file: ../secrets/db_password.txt
  db_name:
    file: ../secrets/db_database.txt
  db_root_password:
    file: ../secrets/db_root_password
