services:
  mariadb:
    build: ./requirements/mariadb/
    restart: unless-stopped
    volumes:
      - mariadb:/var/lib/mariadb
    networks:
      - inception
    env_file:
      - .env
    secrets:
      - db_user
      - db_password
      - db_name
  nginx:
    build: ./requirements/nginx/
    restart: unless-stopped
    depends_on:
      - wordpress
    ports:
      - "443:443"
    volumes:
      - wordpress:/var/www/html
    networks:
      - inception
    env_file: .env
  wordpress:
    build: ./requirements/wordpress/
    restart: unless-stopped
    depends_on:
      - mariadb
    volumes:
      - wordpress:/var/www/html
    networks:
      - inception
    env_file:
      - .env
    secrets:
      - db_user
      - db_password
      - db_name
      - wp_user
      - wp_password
      - wp_email
      - wp_basic_user
      - wp_basic_email
      - wp_basic_password

volumes:
  mariadb:
    driver: local
    driver_opts:
      type: none
      o: 'bind'
      device: /home/jazema/data/database
  wordpress:
    driver: local
    driver_opts:
      type: none
      o: 'bind'
      device: /home/jazema/data/wordpress

networks:
  inception:
    driver: bridge

secrets:
  db_user:
    file: ../secrets/db_user.txt
  db_password:
    file: ../secrets/db_password.txt
  db_name:
    file: ../secrets/db_database.txt
  db_root_password:
    file: ../secrets/db_root_password
  wp_user:
    file: ../secrets/wp_user.txt
  wp_password:
    file: ../secrets/wp_password.txt
  wp_email:
    file: ../secrets/wp_email.txt
  wp_basic_user:
    file: ../secrets/wp_basic_user.txt
  wp_basic_password:
    file: ../secrets/wp_basic_password.txt
  wp_basic_email:
    file: ../secrets/wp_basic_email.txt
